### PR TITLE
Updated regex, added clear function

### PR DESCRIPTION
**Pull request by FabioRosado**
- The regex wasn't setup properly and when you do help skills it would show both the help function and the help skill function. Now, that doesn't happen (sorry still trying to wrap my head around regex).
- Updated README so it contains the new functions
- Changed the name of the stop function (Not sure if in this case, the function name is important but since there was one called reload already I changed it)
- Created a clear function to be used in the shell. This was simply because the shell was getting crowded with error messages when I tried a few things so with clear opsdroid will just print 25 new lines and keep things tidy. (Let me know if you are okay with it)

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Thanks for this.

You might want to look into printing a [clear screen character](https://stackoverflow.com/questions/5367068/clear-a-terminal-screen-for-real) rather than printing 25 blank lines.

**Comment by FabioRosado** [comment]
Thank you, Jacob I didn't know about the clear screen character before

**Comment by jacobtomlinson** [comment]
:+1:

Have you tested this? I assumed that simply responding with the hex code for the clear character might be a bit optimistic. But if it works it works!

**Comment by FabioRosado** [comment]
Yeah  I tested it. I think the code works because you use a print statment on the message.respond method.

**Comment by jacobtomlinson** [comment]
Neat.

**Pull request merged**
